### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by Aemande123**
Create zh_cn.json 1.15

In addition
Can I repost your mods(Keys4Gamemode) to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China.

I will not provide download sources other than Curseforge

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

### CODE REVIEW

**Comment by DenisD3D** [comment]
Thanks for your pull request. That awesome to have this mod translated in chiness.
For the repost on mcbbs I have no problem while you gave me credits, use curseforge download links and link back to the curseforge project page.
In addition can you gave me the post page of mcbbs when you have posted it. I would like to follow   how my mod is used in china 🙃 
Denis

PS : no problem for asking here

**Comment by Aemande123** [comment]
> Thanks for your pull request. That awesome to have this mod translated in chiness.
> For the repost on mcbbs I have no problem while you gave me credits, use curseforge download links and link back to the curseforge project page.
> In addition can you gave me the post page of mcbbs when you have posted it. I would like to follow how my mod is used in china 
> Denis
> 
> PS : no problem for asking here

thank you very much

**Comment by Aemande123** [comment]
> Thanks for your pull request. That awesome to have this mod translated in chiness.
> For the repost on mcbbs I have no problem while you gave me credits, use curseforge download links and link back to the curseforge project page.
> In addition can you gave me the post page of mcbbs when you have posted it. I would like to follow how my mod is used in china 
> Denis
> 
> PS : no problem for asking here

Repost: https://www.mcbbs.net/thread-1008611-1-1.html

**Comment by DenisD3D** [comment]
👌

**Pull request merged**
